### ISSUE TITLE
need generateTemplate.sh for ODM/Liberty (standard, non-container) using  Okta OIDC 

### ISSUE THREAD

**Issue by rscher** [DecisionsDev/odm-docker-kubernetes#116]
Hi Laurant and Team-

This is a useful script when using Okta OIDC, to generate the correct params.
We need this for ODM/Liberty standard installs (**not k8s / containers)** also (2 customers need it)

any chance you can provide or modify generateTemplate.sh. for that install as well ?

./generateTemplate.sh -i <OKTA_CLIENT_ID> -x <OKTA_CLIENT_SECRET> -n <OKTA_SERVER_NAME> -g <OKTA_ODM_GROUP> -s <OKTA_API_SCOPE>

**Comment by lgrateau** [comment]
@PYLochou could you take a look ?

**Comment by lgrateau** [comment]
@rscher This repository and instruction is **only** for container. Please enter an RFE to our OM for this request
