### ISSUE TITLE
Unable to get the ODM External URL.

### ISSUE THREAD

**Issue by vasu1261** [DecisionsDev/odm-docker-kubernetes#126]
Hi Team,

We have been created EKS and as per below link.
https://github.com/DecisionsDev/odm-docker-kubernetes/blob/8.11.0.0/platform/eks/README.md 
 and we can see the ODM Components are running fine. 
But now we are unable to get the url for the Decision centre using below. And while using the kubectl get ingress , getting the below error.
Can you pls assist on below. 

Command :

export ROOTURL=$(kubectl get ingress jpmccompany-odm-ingress | awk '{print $4}' | tail -1)

Error:

[cloudshell-user@ip-10-0-164-113 ~]$ kubectl get ingress jpmccompany-odm-ingress
NAME                      CLASS    HOSTS   ADDRESS   PORTS   AGE
jpmccompany-odm-ingress   <none>   *                 80      14h
[cloudshell-user@ip-10-0-164-113 ~]$ kubectl describe ingress jpmccompany-odm-ingress
Name:             jpmccompany-odm-ingress
Namespace:        default
Address:          
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
Rules:
  Host        Path  Backends
  ----        ----  --------
  *           
              /res                  jpmccompany-odm-decisionserverconsole:9443 (192.168.184.127:9443)
              /decisioncenter       jpmccompany-odm-decisioncenter:9453 (192.168.85.15:9453)
              /decisioncenter-api   jpmccompany-odm-decisioncenter:9453 (192.168.85.15:9453)
              /DecisionService      jpmccompany-odm-decisionserverruntime:9443 (192.168.109.27:9443)
              /DecisionRunner       jpmccompany-odm-decisionrunner:9443 (192.168.189.173:9443)
Annotations:  alb.ingress.kubernetes.io/backend-protocol: HTTPS
              alb.ingress.kubernetes.io/certificate-arn: arn:aws:iam::002768222163:server-certificate/mycompany
              alb.ingress.kubernetes.io/scheme: internet-facing
              kubernetes.io/ingress.class: alb
              meta.helm.sh/release-name: jpmccompany
              meta.helm.sh/release-namespace: default
Events:
  Type     Reason            Age   From     Message
  ----     ------            ----  ----     -------
  Warning  FailedBuildModel  115m  ingress  Failed build model due to WebIdentityErr: failed to retrieve credentials
caused by: AccessDenied: Not authorized to perform sts:AssumeRoleWithWebIdentity
           status code: 403, request id: e2b175e7-dc81-42cb-8da8-4290b8a8bb7e
  Warning  FailedBuildModel  98m  ingress  Failed build model due to WebIdentityErr: failed to retrieve credentials
caused by: AccessDenied: Not authorized to perform sts:AssumeRoleWithWebIdentity
           status code: 403, request id: fa7338d0-a127-4072-bde7-ae9c9f7d9791
  Warning  FailedBuildModel  82m  ingress  Failed build model due to WebIdentityErr: failed to retrieve credentials
caused by: AccessDenied: Not authorized to perform sts:AssumeRoleWithWebIdentity

[cloudshell-user@ip-10-0-164-113 ~]$ kubectl logs -n kube-system deployment.apps/aws-load-balancer-controller
Found 2 pods, using pod/aws-load-balancer-controller-77c858d97c-bzflz
{"level":"info","ts":1661284298.8700292,"msg":"version","GitVersion":"v2.4.3","GitCommit":"6d3e976e3f60dc4588c01bad036d77c127a68e71","BuildDate":"2022-08-09T20:57:15+0000"}
{"level":"info","ts":1661284298.9182322,"logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":":8080"}
{"level":"info","ts":1661284298.9213626,"logger":"setup","msg":"adding health check for controller"}
{"level":"info","ts":1661284298.9214666,"logger":"controller-runtime.webhook","msg":"registering webhook","path":"/mutate-v1-pod"}
{"level":"info","ts":1661284298.9215732,"logger":"controller-runtime.webhook","msg":"registering webhook","path":"/mutate-elbv2-k8s-aws-v1beta1-targetgroupbinding"}
{"level":"info","ts":1661284298.9216375,"logger":"controller-runtime.webhook","msg":"registering webhook","path":"/validate-elbv2-k8s-aws-v1beta1-targetgroupbinding"}
{"level":"info","ts":1661284298.9217162,"logger":"controller-runtime.webhook","msg":"registering webhook","path":"/validate-networking-v1-ingress"}
{"level":"info","ts":1661284298.9217856,"logger":"setup","msg":"starting podInfo repo"}
I0823 19:51:40.921964       1 leaderelection.go:243] attempting to acquire leader lease kube-system/aws-load-balancer-controller-leader...
{"level":"info","ts":1661284300.92234,"logger":"controller-runtime.manager","msg":"starting metrics server","path":"/metrics"}
{"level":"info","ts":1661284300.9224517,"logger":"controller-runtime.webhook.webhooks","msg":"starting webhook server"}
{"level":"info","ts":1661284300.9227476,"logger":"controller-runtime.certwatcher","msg":"Updated current TLS certificate"}
{"level":"info","ts":1661284300.9228306,"logger":"controller-runtime.webhook","msg":"serving webhook server","host":"","port":9443}
{"level":"info","ts":1661284300.9392436,"logger":"controller-runtime.certwatcher","msg":"Starting certificate watcher"}
I0823 19:51:56.771813       1 leaderelection.go:253] successfully acquired lease kube-system/aws-load-balancer-controller-leader
{"level":"info","ts":1661284316.772044,"logger":"controller-runtime.manager.controller.targetGroupBinding","msg":"Starting EventSource","reconciler group":"elbv2.k8s.aws","reconciler kind":"TargetGroupBinding","source":"kind source: /, Kind="}
{"level":"info","ts":1661284316.772114,"logger":"controller-runtime.manager.controller.targetGroupBinding","msg":"Starting EventSource","reconciler group":"elbv2.k8s.aws","reconciler kind":"TargetGroupBinding","source":"kind source: /, Kind="}
{"level":"info","ts":1661284316.7721221,"logger":"controller-runtime.manager.controller.targetGroupBinding","msg":"Starting EventSource","reconciler group":"elbv2.k8s.aws","reconciler kind":"TargetGroupBinding","source":"kind source: /, Kind="}
{"level":"info","ts":1661284316.7721272,"logger":"controller-runtime.manager.controller.targetGroupBinding","msg":"Starting EventSource","reconciler group":"elbv2.k8s.aws","reconciler kind":"TargetGroupBinding","source":"kind source: /, Kind="}
{"level":"info","ts":1661284316.772133,"logger":"controller-runtime.manager.controller.targetGroupBinding","msg":"Starting Controller","reconciler group":"elbv2.k8s.aws","reconciler kind":"TargetGroupBinding"}
{"level":"info","ts":1661284316.7724104,"logger":"controller-runtime.manager.controller.ingress","msg":"Starting EventSource","source":"channel source: 0xc0005bc0f0"}
{"level":"info","ts":1661284316.7724564,"logger":"controller-runtime.manager.controller.ingress","msg":"Starting EventSource","source":"channel source: 0xc0005bc140"}
{"level":"info","ts":1661284316.772479,"logger":"controller-runtime.manager.controller.ingress","msg":"Starting EventSource","source":"kind source: /, Kind="}
{"level":"info","ts":1661284316.772487,"logger":"controller-runtime.manager.controller.ingress","msg":"Starting EventSource","source":"kind source: /, Kind="}
{"level":"info","ts":1661284316.7724926,"logger":"controller-runtime.manager.controller.ingress","msg":"Starting EventSource","source":"channel source: 0xc0005bc190"}
{"level":"info","ts":1661284316.7725155,"logger":"controller-runtime.manager.controller.ingress","msg":"Starting EventSource","source":"channel source: 0xc0005bc550"}
{"level":"info","ts":1661284316.7725365,"logger":"controller-runtime.manager.controller.ingress","msg":"Starting EventSource","source":"kind source: /, Kind="}
{"level":"info","ts":1661284316.772544,"logger":"controller-runtime.manager.controller.ingress","msg":"Starting EventSource","source":"kind source: /, Kind="}
{"level":"info","ts":1661284316.7725508,"logger":"controller-runtime.manager.controller.ingress","msg":"Starting Controller"}
{"level":"info","ts":1661284316.772676,"logger":"controller-runtime.manager.controller.service","msg":"Starting EventSource","source":"kind source: /, Kind="}
{"level":"info","ts":1661284316.7727003,"logger":"controller-runtime.manager.controller.service","msg":"Starting Controller"}
{"level":"info","ts":1661284316.8727598,"logger":"controller-runtime.manager.controller.service","msg":"Starting workers","worker count":3}
{"level":"info","ts":1661284316.8730266,"logger":"controller-runtime.manager.controller.ingress","msg":"Starting workers","worker count":3}
{"level":"info","ts":1661284316.874668,"logger":"controller-runtime.manager.controller.targetGroupBinding","msg":"Starting workers","reconciler group":"elbv2.k8s.aws","reconciler kind":"TargetGroupBinding","worker count":3}
{"level":"error","ts":1661284316.9202325,"logger":"controller-runtime.manager.controller.ingress","msg":"Reconciler error","name":"jpmccompany-odm-ingress","namespace":"default","error":"WebIdentityErr: failed to retrieve credentials\ncaused by: AccessDenied: Not authorized to perform sts:AssumeRoleWithWebIdentity\n\tstatus code: 403, request id: 716a6415-bd6e-4f5d-ae71-7aac7107d3d7"}
{"level":"error","ts":1661284316.9313476,"logger":"controller-runtime.manager.controller.ingress","msg":"Reconciler error","name":"jpmccompany-odm-ingress","namespace":"**### default","error":"WebIdentityErr: **failed to retrieve credentials\ncaused by: AccessDenied: Not authorized to perform sts:AssumeRoleWithWebIdentity\n\tstatus code: 403**,** request id: ### 7b0a51db-d4b2-4da0-8c10-5dac7d616a4f"}
{"level":"error","ts":1661284316.9463332,"logger":"controller-runtime.manager.controller.ingress","msg":"Reconciler error","name":"jpmccompany-odm-ingress","namespace":"default","error":"WebIdentityErr: failed to ret

Thanks & Regards,
Srinivasa M.

**Comment by mmouly** [comment]
Hello @vasu1261 ,
You get this error when the ALB Load Balancer Controller is created with a resource already consumed by an other cluster.
Pay attention when executing the ALB Load Balancer Controller following https://docs.aws.amazon.com/eks/latest/userguide/aws-load-balancer-controller.html, all resources AWSLoadBalancerControllerIAMPolicy, aws-load-balancer-controller must be created and dedicated to your own ALB Load Balancer Controller, if you reuse one that already exists, there is a lot of probability that you get this error.
So, unfortunately, the solution is to recreated your ALB Load Balancer Controller.
You can also have a try with NGINX Ingress Controller https://github.com/DecisionsDev/odm-docker-kubernetes/blob/8.11.0.0/platform/eks/README-NGINX.md that doesn't deal with all the EKS security/identity API.

Hope this helps
