### ISSUE TITLE
org.h2.jdbc.JdbcSQLSyntaxErrorException: Sequence "SYSTEM_SEQUENCE_D05F97DF_165C_4CEC_B9AA_2CFE20B56F97" already exists; SQL statement:

### ISSUE THREAD

**Issue by ibmaaronchen** [DecisionsDev/odm-docker-kubernetes#127]
TS010730880

Client has issue with installing on OCP, but not ICP

helm install lrc-odm-dev --set license=accept  --set usersPassword=odmAdmin --set internalDatabase.persistence.enabled=true --set internalDatabase.persistence.useDynamicProvisioning=true ibm-charts/ibm-odm-dev 

Solution: set internalDatabase.populateSampleData=false
Client suggest to set this by default

--
Name:         lrc-odm-dev-ibm-odm-dev-766fcf8bf9-wzf24
Namespace:    lrc-odm-dev
Priority:     0
Node:         opcgg008401083-dev-ocp4-worker3/10.205.52.98
Start Time:   Tue, 27 Sep 2022 09:42:59 -0400
Labels:       app=ibm-odm-dev
              app.kubernetes.io/instance=ibm-odm-dev
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=ibm-odm-dev
              chart=ibm-odm-dev-22.1.0
              helm.sh/chart=ibm-odm-dev
              heritage=Helm
              pod-template-hash=766fcf8bf9
              release=lrc-odm-dev
              run=ibm-odm-dev
Annotations:  k8s.v1.cni.cncf.io/network-status:
                [{
                    "name": "openshift-sdn",
                    "interface": "eth0",
                    "ips": [
                        "172.20.3.136"
                    ],
                    "default": true,
                    "dns": {}
                }]
              k8s.v1.cni.cncf.io/networks-status:
                [{
                    "name": "openshift-sdn",
                    "interface": "eth0",
                    "ips": [
                        "172.20.3.136"
                    ],
                    "default": true,
                    "dns": {}
                }]
              openshift.io/scc: restricted
              productID: 7b1b6b93868c4468abbe83421c00f667
              productMetric: FREE
              productName: IBM Operational Decision Manager for Developers
              productVersion: 8.11.0.1
Status:       Running
IP:           172.20.3.136
IPs:
  IP:           172.20.3.136
Controlled By:  ReplicaSet/lrc-odm-dev-ibm-odm-dev-766fcf8bf9
Containers:
  ibm-odm-dev:
    Container ID:   cri-o://da3c166bca25e8139be3a805bf88567642ef54e43d016963d3fe300a5cc9c41a
    Image:          icr.io/odm-k8s/odm:8.11.0.1_22.1.0-amd64
    Image ID:       icr.io/odm-k8s/odm@sha256:82cefb305172a70139e6488b275e3310436389d71e37399250000f1ee6adf30c
    Port:           9060/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Tue, 27 Sep 2022 09:44:54 -0400
      Finished:     Tue, 27 Sep 2022 09:44:58 -0400
    Ready:          False
    Restart Count:  4
    Limits:
      cpu:                2
      ephemeral-storage:  500Mi
      memory:             2Gi
    Requests:
      cpu:                1
      ephemeral-storage:  50Mi
      memory:             1Gi
    Liveness:             http-get http://:9060/decisioncenter/healthCheck delay=0s timeout=1s period=10s #success=1 #failure=10
    Readiness:            http-get http://:9060/decisioncenter/healthCheck delay=10s timeout=1s period=5s #success=1 #failure=45
    Startup:              http-get http://:9060/decisioncenter/healthCheck delay=0s timeout=1s period=10s #success=1 #failure=30
    Environment:
      LICENSE:                accept
      DB_TYPE:                h2
      SAMPLE:                 true
      DC_PERSISTENCE_LOCALE:  en_US
      RELEASE_NAME:           lrc-odm-dev
      USERS_PASSWORD:         <set to the key 'users-password' in secret 'lrc-odm-dev-odm-secret'>  Optional: false
    Mounts:
      /config/dbdata/ from lrc-odm-dev-ibm-odm-dev-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-2jqmj (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  lrc-odm-dev-ibm-odm-dev-volume:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  lrc-odm-dev-odm-pvclaim
    ReadOnly:   false
  kube-api-access-2jqmj:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
    ConfigMapName:           openshift-service-ca.crt
    ConfigMapOptional:       <nil>
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason          Age                    From               Message
  ----     ------          ----                   ----               -------
  Normal   Scheduled       3m                     default-scheduler  Successfully assigned lrc-odm-dev/lrc-odm-dev-ibm-odm-dev-766fcf8bf9-wzf24 to opcgg008401083-dev-ocp4-worker3
  Normal   AddedInterface  2m59s                  multus             Add eth0 [172.20.3.136/23] from openshift-sdn
  Warning  Unhealthy       2m21s (x2 over 2m51s)  kubelet            Startup probe failed: Get "http://172.20.3.136:9060/decisioncenter/healthCheck": dial tcp 172.20.3.136:9060: connect: connection refused
  Normal   Pulled          116s (x4 over 2m59s)   kubelet            Container image "icr.io/odm-k8s/odm:8.11.0.1_22.1.0-amd64" already present on machine
  Normal   Created         116s (x4 over 2m57s)   kubelet            Created container ibm-odm-dev
  Normal   Started         116s (x4 over 2m57s)   kubelet            Started container ibm-odm-dev
  Warning  BackOff         81s (x11 over 2m41s)   kubelet            Back-off restarting failed container

--
logs:
HTTP_PORT unset : set 9060
HTTPS_PORT unset : set 9453
HTTPS_PORT : 9453
HTTP_PORT : 9060
ODM_CONTEXT_ROOT unset : set blank
Exception in thread "main" org.h2.jdbc.JdbcSQLSyntaxErrorException: Sequence "SYSTEM_SEQUENCE_D05F97DF_165C_4CEC_B9AA_2CFE20B56F97" already exists; SQL statement:
         
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_D05F97DF_165C_4CEC_B9AA_2CFE20B56F97" START WITH 65 BELONGS_TO_TABLE [90035-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:573)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.command.ddl.CreateSequence.update(CreateSequence.java:53)
	at org.h2.command.dml.RunScriptCommand.execute(RunScriptCommand.java:79)
	at org.h2.command.dml.RunScriptCommand.update(RunScriptCommand.java:58)
	at org.h2.command.CommandContainer.update(CommandContainer.java:133)
	at org.h2.command.Command.executeUpdate(Command.java:267)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:233)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:205)
	at org.h2.tools.RunScript.processRunscript(RunScript.java:283)
	at org.h2.tools.RunScript.runTool(RunScript.java:141)
	at org.h2.tools.RunScript.main(RunScript.java:70)

**Comment by mmouly** [comment]
Hello @ibmaaronchen,

Unfortunately, I tested the ibm-odm-dev-22.1.0 chart on OCP and I don't reproduce the issue.
The logs you are providing seems to be after a restart of the pod.
It seems there is a problem with the OCP PV, as H2 as an issue with the persistence.
However, I don't understand the reason of the first pod restart.

Can you provide the logs of the pod during the first start ?

Normally, on OCP, you have to let the cluster choose the user that have the permission to write on PV. So, can you relaunch using : 
helm install lrc-odm-dev --set license=accept --set usersPassword=odmAdmin --set internalDatabase.persistence.enabled=true --set internalDatabase.persistence.useDynamicProvisioning=true -**set customization.runAsUser=""** ibm-charts/ibm-odm-dev

Can you also make a start without any associated PV ?
helm install lrc-odm-dev --set license=accept --set usersPassword=odmAdmin --set internalDatabase.persistence.enabled=false ibm-charts/ibm-odm-dev

Thanks for the test
