### ISSUE TITLE
Do we need Decision Runner on a PROD without DC?

### ISSUE THREAD

**Issue by dhpalan** [DecisionsDev/odm-docker-kubernetes#128]
On our Development environment, we run 4 separate Docker images for each ODM Service.
As shown in this picture -> https://github.com/DecisionsDev/odm-ondocker/blob/master/docs/images/Architecture.png

#### But On production we do not run a `Decision Center`.

In this case, we were wondering, if `Decision Runner` is needed on our PROD?
Is Decision Runner used only by Decision Center? If yes, we plan to remove it from PROD.

Any link to a document that explains the purpose or role of each Docker container (ODM Components) will be really helpful.

![image](https://user-images.githubusercontent.com/46791526/198825963-b7d7814b-3937-47e6-8d34-282ddd66cf91.png)

**Comment by dhpalan** [comment]
I found this diagram that shows which component belongs to which stage (development, test, and production)
It seems Decision Center and Decision Runner only belongs to development.

On test, and production we need just Decision Server (Decision Server Runtime, Decision Server Console).

Image from [ODM for production (ibm-odm-prod)](https://www.ibm.com/docs/en/odm/8.11.0?topic=kubernetes-odm-production-odm-prod)
https://www.ibm.com/docs/en/SSQP76_8.11.0/com.ibm.odm.kube/images/diag_install.jpg

**Comment by mmouly** [comment]
Hello, yes, Decision Runner container is not dedicated to production. It's mainly on dev and test.

**Comment by dhpalan** [comment]
Thanks for the confirmation.
I will remove Decision Runner from PROD, as it is only used by Decision Center for testing in our Dev environment.

Could save some resource on our Kubernetes cluster.
