### ISSUE TITLE
Support edge-route on OpenShift

### ISSUE THREAD

**Issue by davidkarlsen** [DecisionsDev/odm-docker-kubernetes#158]
Really a case for https://github.com/IBM/charts - as we use this chart-repo - but it hasn't enabled issues - but it seems the charts have this as upstream for ODM.

Can you support edge-terminated routes in your chart?
https://docs.openshift.com/container-platform/4.12/networking/routes/secured-routes.html#nw-ingress-creating-an-edge-route-with-a-custom-certificate_secured-routes

That way we can piggy-back on the default ingress-controller TLS-certificate and avoid exposing the internal-generated certificates from ODM.

**Comment by lgrateau** [comment]
Sorry for the delay,

This charts is part of the ODM commercial offering. So you should contact the IBM support. 
No plan to add edge-terminated routes. However you can create your own aside the ones created by ODM.
